### ISSUE TITLE
[Suggestion] Conditions commands - /if status poor then "Observe" <wait.3>

### ISSUE THREAD

**Issue by imgidedin** [daemitus/SomethingNeedDoing#10]
Have no idea where to ask stuff about this, so, is there any way to make it check if the condition is poor and observe for 1 turn? That would be a safeguard for Byregots Blessing

**Comment by daemitus** [comment]
the correct place to ask would be right here.

And unfortunately no, there's no conditional logic in place as of yet.
maybe in the distant future.

**Comment by daemitus** [comment]
Hey. I added it :)

/ac whatever <condition.poor>

**Comment by thebinaryeagle** [comment]
Love this addition but would it be possible to add a 'not' version of the modifier? Some macros, such as the one in this image, rely on the Byregots to land inside Innovation which can't happen if you're poor-proofing the macro using Observe/Tricks of the Trade. It'd be super helpful to be able to have `/ac "Great Strides" <condition.not.excellent>` if it's not too much of a hassle to implement.

![image](https://user-images.githubusercontent.com/60583962/147510684-7e896139-5772-4765-84c5-f0f343705ac5.png)

**Comment by daemitus** [comment]
ill do it today
