### ISSUE TITLE
/send CONTRL+V not working

### ISSUE THREAD

**Issue by WilliamW1979** [daemitus/SomethingNeedDoing#108]
So when you do a line like:

/send CONTROL+V

It give this error:

[SND] Unexpected error.

I even tried using code directly from the github (compiling it myself and replacing the files) but the error is still the same.

Now I experimented and these all work:

/send CONTROL
/send LCONTROL
/send RCONTROL
/send v

When I do this:

/send 

I get [SND] Syntax error: /send

Researching your code, the only type the Unexpected error comes up is when you are in the RunMacro function and you are catching the second Exception.

That should give you an idea on where the problem lies. 

private void RunMacro(MacroNode node)
{
    try
    {
        Service.MacroManager.EnqueueMacro(node);
    }
    catch (MacroSyntaxError ex)
    {
        Service.ChatManager.PrintError($"{ex.Message}");
    }
    catch (Exception ex)
    {
        Service.ChatManager.PrintError($"Unexpected error");
        PluginLog.Error(ex, "Unexpected error");
    }
}

When I commented out that catch, it stopped sending the error but did not do the CONTROL+V as it should so your problem is somewhere in your function in the try statement (Service.MacroManager.EnqueueMacro(node)).

Considering that the function is:

public void EnqueueMacro(MacroNode node)
{
    this.macroStack.Push(new ActiveMacro(node));
    this.pausedWaiter.Set();
}

That means your problem is either the Push or the Set function causing some error that it is throwing the exception. Hopefully this helps you figure out what is happening.

**Comment by WilliamW1979** [comment]
I was wrong, the error is definitely in the Parse function, it never reaches the Push().

I threw in some Lines to log to a log.txt file and it definitely got into the Parse function but it never got to the Push:

public static SendCommand Parse(string text)
{
    string path = @"D:\Log.txt";
    using (FileStream fs = File.OpenWrite(path))
    {
        byte[] bytes = Encoding.UTF8.GetBytes("We Got Here (Parse)!");
        fs.Write(bytes, 0, bytes.Length);
    }
    _ = WaitModifier.TryParse(ref text, out var waitModifier);

    var match = Regex.Match(text);
    if (!match.Success)
        throw new MacroSyntaxError(text);

    var nameValue = ExtractAndUnquote(match, "name");
    var vkCodes = nameValue.Split("+")
        .Select(name =>
        {
            if (!Enum.TryParse<VirtualKey>(nameValue, true, out var vkCode))
                throw new MacroCommandError("Invalid virtual key");

            return vkCode;
        })
        .ToArray();

    return new SendCommand(text, vkCodes, waitModifier);
}

I will throw in some more log files to pin down the exact point of the problem

**Comment by WilliamW1979** [comment]
Okay, pinned the problem for you!

public static SendCommand Parse(string text)
{
    string path = @"D:\Log.txt";
    using (FileStream fs = File.OpenWrite(path))
    {
        byte[] bytes = Encoding.UTF8.GetBytes("We Got Here (Parse)!");
        fs.Write(bytes, 0, bytes.Length);
    }
    _ = WaitModifier.TryParse(ref text, out var waitModifier);

    using (FileStream fs = File.OpenWrite(path))
    {
        byte[] bytes = Encoding.UTF8.GetBytes("We Got Here (Pre Regex)!");
        fs.Write(bytes, 0, bytes.Length);
    }

    var match = Regex.Match(text);
    if (!match.Success)
        throw new MacroSyntaxError(text);

    using (FileStream fs = File.OpenWrite(path))
    {
        byte[] bytes = Encoding.UTF8.GetBytes("We Got Here (After Regex)!");
        fs.Write(bytes, 0, bytes.Length);
    }

    var nameValue = ExtractAndUnquote(match, "name");

    using (FileStream fs = File.OpenWrite(path))
    {
        byte[] bytes = Encoding.UTF8.GetBytes("We Got Here (Pre +)!");
        fs.Write(bytes, 0, bytes.Length);
    }

    var vkCodes = nameValue.Split("+")
        .Select(name =>
        {
            if (!Enum.TryParse<VirtualKey>(nameValue, true, out var vkCode))
                throw new MacroCommandError("Invalid virtual key");

            return vkCode;
        })
        .ToArray();

    using (FileStream fs = File.OpenWrite(path))
    {
        byte[] bytes = Encoding.UTF8.GetBytes("We Got Here (Post +)!");
        fs.Write(bytes, 0, bytes.Length);
    }

    return new SendCommand(text, vkCodes, waitModifier);
}

So your problem is definitely in this line:

var vkCodes = nameValue.Split("+")
    .Select(name =>
    {
        if (!Enum.TryParse<VirtualKey>(nameValue, true, out var vkCode))
            throw new MacroCommandError("Invalid virtual key");

        return vkCode;
    })
    .ToArray();

This is what you need to fix as it is causing an error. The log files get to the (Pre +) but never reach the (Post +) so somewhere between, that line, is causing your problems.

**Comment by WilliamW1979** [comment]
Okay, for now I replaced your code with this:

for (int myCount = 0; myCount < mySub.Count(); myCount++)
{
    switch (mySub[myCount])
    {
        case "CONTROL":
            vkCodes[myCount] = VirtualKey.CONTROL;
            break;
        case "V":
            vkCodes[myCount] = VirtualKey.V;
            break;
        case "SHIFT":
            vkCodes[myCount] = VirtualKey.SHIFT;
            break;
        default:
            throw new MacroSyntaxError("Virtual Key not in the list!");
    }
}

It is crude but it works properly. I would literally have to add everything in there to get other keys to work but for now it should give you an idea of what is the problem and how to fix it.

**Comment by WilliamW1979** [comment]
Sorry, I just got an earful from my student that I messed up her other macro because I messed up the other virtual keys. So I fixed it so her old macros will work now with the new code. This is the finished part:

```    public static SendCommand Parse(string text)
    {
        _ = WaitModifier.TryParse(ref text, out var waitModifier);

        var match = Regex.Match(text);
        if (!match.Success)
            throw new MacroSyntaxError(text);

        var nameValue = ExtractAndUnquote(match, "name");

        int freq = nameValue.Count(f => (f == '+'));
        string[] mySub = nameValue.Split('+');
        var vkCodes = new VirtualKey[mySub.Count()];
        if (freq > 0)
        {

            for (int myCount = 0; myCount < mySub.Count(); myCount++)
            {
                switch (mySub[myCount])
                {
                    case "CONTROL":
                        vkCodes[myCount] = VirtualKey.CONTROL;
                        break;
                    case "V":
                        vkCodes[myCount] = VirtualKey.V;
                        break;
                    case "SHIFT":
                        vkCodes[myCount] = VirtualKey.SHIFT;
                        break;
                    default:
                        throw new MacroSyntaxError("Virtual Key not in the list!");
                }
            }
        }
        else
        {
            vkCodes = nameValue.Split("+").Select(name =>
            {
                if (!Enum.TryParse<VirtualKey>(nameValue, true, out var vkCode))
                    throw new MacroCommandError("Invalid virtual key");

                return vkCode;
            })
            .ToArray();
        }

        return new SendCommand(text, vkCodes, waitModifier);
    }```

**Comment by WilliamW1979** [comment]
Oh, so there is no one that can really update this then. Would you like me to work on an update for you?

**Comment by WilliamW1979** [comment]
You were right, I changed what you suggested and your code worked. You will want to change the nameValue in the Enum to name. So have it look like this:

```        var vkCodes = nameValue.Split("+").Select(name =>
        {
            if (!Enum.TryParse<VirtualKey>(name, true, out var vkCode))
                throw new MacroCommandError("Invalid virtual key");

            return vkCode;
        })
           .ToArray();```

And that will fix all the errors and have it access all the Virtual keys.

**Comment by WilliamW1979** [comment]
I don't use github much, I am most of an old school programmer. So I created a fork, put the updates in. Also did it to your site. How do I send the binaries up to you?

**Comment by daemitus** [comment]
If you hit the pull request tab up top on GitHub and make a new one, it
should let you target your fork

**Comment by WilliamW1979** [comment]
Okay done, I think I did it right.
