### ISSUE TITLE
[Suggestion] Require minimum Craft/Control/CP like /require "Well Fed"

### ISSUE THREAD

**Issue by imgidedin** [daemitus/SomethingNeedDoing#11]
That could prevent mistaken when you forgot to repair something.

For example, we could have:

/require "Well Fed"
/require craftsmanship 2793
/require cp 620

And if it fails, it would warn and pause the macro.

**Comment by daemitus** [comment]
not a bad idea

**Comment by daemitus** [comment]
soon: `/requirestats 2700 2600 500`

**Comment by daemitus** [comment]
craftsmanship, control, cp
