### ISSUE TITLE
[Feature? Request] LUA Code Sample

### ISSUE THREAD

**Issue by ladyredxiv** [daemitus/SomethingNeedDoing#111]
Wasn't rightly sure how to tag this, but I have been working on a LUA script for the past couple days that I would be happy to share with folks through this Git as a code sample that they can use. What would be the best way to share it along?

**Comment by ladyredxiv** [comment]
Reopened because I'm a dense mf... *sigh* But yes, question remains!

**Comment by TheWalkingDude19** [comment]
I think some people have posted some in the Wiki. If that's what you're looking to do.

![image](https://user-images.githubusercontent.com/122064331/210905416-a8cd80ad-65e8-496e-9d91-6ed7208a6ae8.png)

**Comment by ladyredxiv** [comment]
Ah, thank you! I derped and didn't notice I could just add a page in there
