### ISSUE TITLE
Question about the <echo> parameter

### ISSUE THREAD

**Issue by ladyredxiv** [daemitus/SomethingNeedDoing#112]
So, I'm using a do while loop for my LUA script, and I was wondering if there's a way to invoke the echo parameter akin to a print? For example, I would like to echo craftAmount after this:

`craftAmount = craftAmount + 1`

That way I can tell how far along things are. Any insight would be much appreciated!

Edit: Not currently using the ticker with my loop anymore, but the question remains <3

**Comment by daemitus** [comment]
The basic lua idea would be similar to this, using the `..` operator for string concatenation.
print("abc" .. "def") -- Would print "abcdef".

So you could yield a `yield("/echo Amount is " .. $craftAmount)`

or something similar to that.
