### ISSUE TITLE
Can't find the link to get Plugin

### ISSUE THREAD

**Issue by Nyhlaam** [daemitus/SomethingNeedDoing#115]
I'm not sure why or how but looking at the Github.. I can't seem to find the link that you need to post onto Dalamud to get the Plugin.. Maybe it's meant to be like that but I would like to ask before it's something else uncommon.

**Comment by SmoothJaz** [comment]
same, ended up finding this plugin through the aku repo but wanted to get ti from the source instead... only to find i dont know how to actually get the link lol

**Comment by Nyhlaam** [comment]
Thank u v much!
