### ISSUE TITLE
EW Update?

### ISSUE THREAD

**Issue by calmcacil** [daemitus/SomethingNeedDoing#12]
I know we're still pretty early on, but I was wondering if this was planned to get updated for EW in the near future.

Also do you have a ko-fi link or some way to support your work, because its saved me a lot of frustration and its worth a couple of bucks.

**Comment by daemitus** [comment]
I pushed this last night, unless GitHub didn't work

**Comment by calmcacil** [comment]
github's showing last commit in October.

**Comment by daemitus** [comment]
pushed

**Comment by calmcacil** [comment]
Sweet, keep up the good work!
