### ISSUE TITLE
Plugin no longer recognises the Click Synthesize command.

### ISSUE THREAD

**Issue by Kyla772** [daemitus/SomethingNeedDoing#13]
Just like the header really. Mostly everything else seems to work fine, but the /click Synthesize command does not work anymore. I have even trued putting Synthesize in speech marks, but no avail. I have copied the error message that pops up. 

[14:28][SND] Click not found: Failure while running /click Synthesize (step 2)

**Comment by daemitus** [comment]
Try lowercase

**Comment by Kyla772** [comment]
Yep, switching it to lowercase worked. Thank you! I can't believe I never thought of that!

**Comment by daemitus** [comment]
Excellent, gl crafting :)
