### ISSUE TITLE
[FEATURE REQUEST] Loop Counter in GUI

### ISSUE THREAD

**Issue by kgetit** [daemitus/SomethingNeedDoing#15]
This plugin is amazing. If you could add a loop counter to the GUI, that would be icing to the cake. Thank you in advance!

**Comment by daemitus** [comment]
how about an optional `<echo>` modifier on `/loop` that prints out the loops remaining

**Comment by daemitus** [comment]
made the modifier, let me know how you like it. I'll have a version ready in a little bit hopefully.

**Comment by kgetit** [comment]
The <echo> command works like a charm. 👍
