### ISSUE TITLE
[BUG] Invisible Window with no click through

### ISSUE THREAD

**Issue by kgetit** [daemitus/SomethingNeedDoing#16]
While and after using the plugin, there is an invisible window on the lower right section of the screen that you cannot click through. After testing all other plugins, this one seems to be the cause. In-game UI cannot be activated/clicked in the area until you restart the game.

**Comment by daemitus** [comment]
Are you able to replicate this often?

If you use the /xldev command, goto GUI, then Draw Metrics, it can allow you to outline every imgui window and what it's been named. If there is truly a hidden window blocking input, this will identify the culprit.

**Comment by kgetit** [comment]
Sorry for the late reply. I figured it out. It's not your plugin. It's when I use the craft window, my profile for icue switches and there's a window from it that is invisible. I have to manually close and restart icue for it to go away. Very frustrating, but, it's not your awesome plugin. Please close.

**Comment by daemitus** [comment]
good to know, thank you.
