### ISSUE TITLE
Assign macro to button?

### ISSUE THREAD

**Issue by ripdog** [daemitus/SomethingNeedDoing#17]
Thanks for this addon, it really fills the gaps in the macro system gooooood!

But it'd be great if the macros could be assigned to an action bar button like a normal macro. I guess the easy way to do this is to modify the /pcraft command to accept an argument of a macro name.

**Comment by daemitus** [comment]
added. look at /pcraft help for the cli info.

**Comment by ripdog** [comment]
Thanks so much, @daemitus ! However, I haven't been able to get it to work. See screenshot: https://i.imgur.com/wcN1boD.png

At first the macro name had spaces, so I renamed it to remove them, but still no luck. Any advice?

Here's my plugin config if it's helpful: [SomethingNeedDoing.zip](https://github.com/daemitus/SomethingNeedDoing/files/7780932/SomethingNeedDoing.zip)

**Comment by daemitus** [comment]
thanks, ill take a look as to whats going on.

**Comment by daemitus** [comment]
oh i fucked it up. i had it as "runmacro" and was slicing off the first 9
characters.
now its run and still 9 characters.

**Comment by daemitus** [comment]
pushing a fix, re-open if the issue persists please.

**Comment by ripdog** [comment]
Brilliant, works great. Thanks!
