### ISSUE TITLE
[Feature Request] Pause at Next Loop Button

### ISSUE THREAD

**Issue by keoShine** [daemitus/SomethingNeedDoing#19]
It'd be nice if there were an additional "Pause" button that continued the macro until the next time it encountered the "/loop" command.. It's a bit frustrating that if I need to stop crafting to stand up and extract materia or repair my gear or turn in collectibles to empty out my inventory, I have to either pause exactly on the right step to prevent the next loop from starting or else finish out the macro manually.. A button that would finish out the current loop but not start the next one would be an appreciated feature if possible..

**Comment by daemitus** [comment]
on next release, control-click on the pause button will pause after the next /loop command.
