### ISSUE TITLE
Loop functionality changed?

### ISSUE THREAD

**Issue by calmcacil** [daemitus/SomethingNeedDoing#20]
Did loop functionality change in a recent update? using <echo> on loop for 10 loops, stops it after the 10 crafts, with the log out put of 1 loop remaining. I dont really mind the change of making the loop number be the amount of crafts wanted but if its the case you probably wanna -1 on loops remaining for the output.

**Comment by daemitus** [comment]
I had reports of it being wonky. Can you link your macro?

This is what ive been using to test.
```
/echo abc <wait.2>
/loop 2 <echo>
```
resulting in
```
abc
[SND] 2 loops remaining
abc
[SND] 1 loop remaining
abc
[SND] 0 loops remaining
```

**Comment by calmcacil** [comment]
I was using this to mass craft some of the new furniture for my house.

`
/click synthesize
/waitaddon "Synthesis" <wait.1>
/ac Veneration <wait.2>
/ac Groundwork <wait.3>
/ac Groundwork <wait.3>
/ac Groundwork <wait.3>
/waitaddon "RecipeNote" <wait.3>
/loop 10 <echo>
`

stops at 1 remaining and clears the queue, no error in chat.

**Comment by daemitus** [comment]
yeah, im bad at this. ill fix it shortly.

**Comment by daemitus** [comment]
1.2.1.5 should fix this. re-open if i have continued to be dumb.
