### ISSUE TITLE
[Feature Request] Stop and clean up Macro on Completed Craft

### ISSUE THREAD

**Issue by imynwulf** [daemitus/SomethingNeedDoing#22]
Is it possible to detect when a craft has been completed and auto-clear the rest of the macro?

I've got a macro that works for like 90% of my items, but occasionally if the progress is a little lower then expected, I'm left with one careful synth at the end that sits in the macro queue.

**Comment by daemitus** [comment]
The unsafe modifier doesn't wait for a server response on actions, that
might work for now.
