### ISSUE TITLE
[Feature Request] Interrupt next loop command

### ISSUE THREAD

**Issue by DarkDestry** [daemitus/SomethingNeedDoing#23]
In the middle of a craft, you want to finish the current craft but stop crafting after the current craft. Instead of waiting for the next loop command to come around to clear the macro queue, You can interrupt the next loop command. 

Alternatively, in the macro queue, allow right click to delete command. This means we can right click the loop command at the end and it will stop looping.

**Comment by daemitus** [comment]
you can control-click the pause (and soon the stop/trash button) to perform
at the next /loop instead of immediately. /command options will be
available soon.
