### ISSUE TITLE
using condition results in aborted macro

### ISSUE THREAD

**Issue by Tysaki** [daemitus/SomethingNeedDoing#25]
hey, it seems that as soon as a condition is met, for example <condition.poor>, the following /ac cant be properly executed because the skill used by the condition has no wait on it.

i tried chaining the condition with wait
```
/ac Observe <condition.poor> <wait.2>
/ac Observe <condition.poor wait.2>
```
but had no luck.

Thank you so much for your work on the plugin, its really great so far.

**Comment by Tysaki** [comment]
just came to my mind, a quick and dirty fix for the issue would be to just add a fixed /wait 3 after the conditial action was executed

**Comment by daemitus** [comment]
can you show me the full macro you were using that you had issues with?

The syntax should be `<condition.whatever> <wait.3>`

**Comment by Tysaki** [comment]
i tried it again today with the syntax you provided and it seems to work. strange. i was sure i tested that. maybe i had a typo somewhere. sorry
