### ISSUE TITLE
[Question] What information do I need to click buttons besides "Synthesize"?

### ISSUE THREAD

**Issue by borkmaster12** [daemitus/SomethingNeedDoing#27]
While browsing the plugin capabilities, I was intrigued by the Click feature. Out of curiousity, I decided to see whether I could click buttons besides Synthesize such as Quick Synthesis, Begin Trial Synthesis, or Quit on the crafting window.

After exhausting the trial-and-error options that seemed most obvious to me, I turned my attention to the /xldata interface. I was able to locate the target window/button data in the "Addon Inspector" view, but wasn't able to turn up a button identifier that compares to the provided "synthesis" example. Would you mind pointing me in the right direction please?

**Comment by daemitus** [comment]
https://github.com/daemitus/ClickLib/tree/master/ClickLib/Clicks

**Comment by borkmaster12** [comment]
Thanks, that's what I needed
