### ISSUE TITLE
[Suggestion] Make loop count equal to number of times macro should loop

### ISSUE THREAD

**Issue by keoShine** [daemitus/SomethingNeedDoing#28]
Currently, Loop appears to work by running through the macro, encountering the /loop command at the end, and _then_ repeating the macro equal to the number of times specified on the loop command.. This results in the first run through of the macro not counting towards the number of loops specified, causing the macro to attempt to run one more loop than what the actual integer on the loop counter is.. It would make more intuitive sense for the loop integer to be the number of times that the macro is run by having the loop count decrement _before_ checking how many loops left to run so that the first run of the macro isn't skipped over when counting loops (e.g., ten loops of the macro would be specified with "/loop 10" rather than "/loop 9")..

**Comment by BeetleLord** [comment]
I agree with this comment, right now if I want to craft 5 copies of an item I must specify "loop 4" which makes little sense.

**Comment by daemitus** [comment]
You're thinking of it as a macro option, do this N times. All it does is cause the macro to start over N times. 

That being said, there will soon be a config option to set /loop as the total iterations, rather than the number of times to restart.
