### ISSUE TITLE
endless loops never stop

### ISSUE THREAD

**Issue by LastExceed** [daemitus/SomethingNeedDoing#32]
i tried 
```
/ac "Summon Carbuncle"
/loop
```
on SMN for testing purposes, and cannot figure out how to make it stop. neither the stop button, nor the commands `/pcraft stop` and `/pcraft stop loop` work. the only way i found was uninstalling the plugin

**Comment by daemitus** [comment]
🤷 works fine for me. 

`/pcraft run test`
`/pcraft stop`
```
/echo test1 <wait.2>
/echo test2 <wait.2>
/echo test3 <wait.2>
/loop
```

**Comment by LastExceed** [comment]
maybe try reproducing with the exact same macro i used?

**Comment by daemitus** [comment]
The "send to chat" part of this uses a queue that schedules each `/ac` to be sent on the next tick. Because there is no wait, and you absolutely need a wait for any /ac command, it sent a bunch of stuff into the queue. This has been fixed, when you stop or pause the chat queue is now cleared.

**Comment by LastExceed** [comment]
ah yes i understand. thanks for the explanation and quick fix!
