### ISSUE TITLE
[Feature requests] Automatic repair

### ISSUE THREAD

**Issue by PotatoSol** [daemitus/SomethingNeedDoing#33]
Would allow for macros like

/click synthesize
/ac [crafting macro]
/loop 100
/repair
/loop

(edit: this actually wouldn't work cus you can't run a loop in the middle of a macro so that would also need to be updated)

**Comment by daemitus** [comment]
you actually can. each loop is tracked separately. i think i'd just have to tweak the loop logic a little to reset itself after reaching the max loop value. 

ANYWAYS. an explicit /repair command will probably never happen. however separate /click commands could potentially be developed if I ever had the time to do it.  The hardest problem is opening the repair window without going through the inventory item context menu. I dont think theres a native /command to open that window normally.

**Comment by PotatoSol** [comment]
I think you could just leave the repair window up throughout the entire
craft and then just do /click "repair all", it'd be a little clunky but
functional

anyways, thanks for the plugin definitely my favorite one i've used!

**Comment by trini0n** [comment]
Just a thought, but maybe you could have settings to set a hotkey for the gear repair shortcut and if someone initiates /repair, it'll send the keystroke to open the menu?

**Comment by daemitus** [comment]
half the problem too, is you cant  repair while crafting/kneeling. So you
need to back out of the menu, which loses your recipe spot :(

**Comment by PotatoSol** [comment]
https://github.com/Saad888/AutoSynthesis

This is a different program that I used before switching to yours that allows you to use food/pot when it ran out, and you can't do those while crafting/kneeling either. I'm not 100% sure, but I think it works by having you start a craft and then cancel the craft, so that you stand up.  As long as you don't do any actions in a craft, all the mats are refunded.  From here, you can click "repair all -> yes" and then "synthesize" again without closing any important windows

**Comment by daemitus** [comment]
there's now a `/click repair_all` and `/click synthesis_quit`. Also, nested looping should be fixed. If you combine this with YesAlready or do the `/click select_yes` yourself, along with some `/waitaddon` commands, you should be able to do it manually for now.

**Comment by PotatoSol** [comment]
Works great! Thanks!
