### ISSUE TITLE
Send function not working

### ISSUE THREAD

**Issue by Nitrodroki** [daemitus/SomethingNeedDoing#34]
A friend uses it fine with the same syntax but my keystate doesnt turn green and no key is processed by the game. I've tried multiple like 
`/send A`
or even 
`/send CONTROL`
Is there some incompatibility with something  that I'm missing ?

**Comment by daemitus** [comment]
whats your macro

**Comment by Nitrodroki** [comment]
edited my  comment, simple keystroke like A

**Comment by Nitrodroki** [comment]
It's very weird, seems like the send is just not working for me at all while my friend is streaming the exact same macro of a simple /send a and it works just fine with his xldata greening up

**Comment by daemitus** [comment]
mmmm. i use some basic windows API functions to send the keystrokes. you might try using something like autohotkey, and see if it works in that. if not, then its gotta be something running on your system, or some config blocking it.

**Comment by Nitrodroki** [comment]
Yeah I use autohotkey quite a bit and it works fine. I'm wondering if it's not some program that blocks it on that like a keyboard or mouse thing like steelseries or razer.

**Comment by daemitus** [comment]
make sure the macro window textbox doesn't have your input still.

**Comment by Nitrodroki** [comment]
I'll try to upload what's happening, because it'es very weird it's as if the send function doesnt have access to the client's keys.

**Comment by daemitus** [comment]
DM me on discord if you want to send the video

**Comment by Nitrodroki** [comment]
[](https://im5.ezgif.com/tmp/ezgif-5-5c28e4eb6e.gif)

**Comment by Nitrodroki** [comment]
It was UAC problems. Some administrator privileges seem to prevent sendmessage from launching. Daemitus has been made aware, and there is a "workaround" by removing UAC so I'm closing the issue.
