### ISSUE TITLE
[Bug] Sometimes, when crafting in Garlemald, the Reflect at the start of a macro gets skipped.

### ISSUE THREAD

**Issue by daria-mianne** [daemitus/SomethingNeedDoing#35]
Plugin version: 1.2.2.0

Issue found while doing precrafts for potions between legendary node spawns. Issue persisted after teleporting out of the zone for a round and coming back. Did not test whether it occurs in other zones, but as of approximately a day and a half ago, it did not occur in the Old Sharlayan Inn Room in over 100 crafts.

I think that it was not an issue with the plugin's detection for failed actions or lag. I think this because I tested it by extending the `/waitaddon` wait duration, pausing the macro during this wait, ensuring that actions were available to use, and observing that upon resuming the macro, the next step executed was Manipulation. As this occurred, both the Reflect and waitaddon lines were removed from the step queue at, as far as my eye could tell, the same time.

Macro:
```
/click synthesize <wait.1>
/waitaddon "Synthesis" <wait.1>
/ac Reflect <wait.3>
/ac Manipulation <wait.2>
/ac "Waste Not II" <wait.2>
/ac Innovation <wait.2>
/ac "Preparatory Touch" <wait.3>
/ac "Preparatory Touch" <wait.3>
/ac "Preparatory Touch" <wait.3>
/ac "Byregot's Blessing" <wait.3>
/ac Veneration <wait.2>
/ac Groundwork <wait.3>
/waitaddon "RecipeNote" <wait.1>
/loop <echo>
```

Recipe: Grade 5 Strength Alkahest
Location: Ilsabard > Garlemald > X: 31.9, Y: 34.8, Z: 0.0 (roughly where the Rime Dolomite / Stonehard Water node spawns)

Observed rate of occurrence 4 in 15. Actual rate possibly much higher or lower due to small sample size.

**Comment by Speshkitty** [comment]
Same issue, crafting in FC house

Macros:

```
/waitaddon RecipeNote <wait.0.5-2>
/click Synthesize
/waitaddon Synthesis <wait.1>

/runmacro 90**/35/2925/7800/0/Y/N

/loop 9 <echo>
/echo Craft finished <se.1>
```


```
/requirestats 3241 3461 645 <wait.2>
/ac Reflect <wait.3>
/ac Manipulation <wait.2>
/ac "Waste Not II" <wait.2>
/ac Innovation <wait.2>
/ac "Preparatory Touch" <wait.3>
/ac "Preparatory Touch" <wait.3>
/ac "Preparatory Touch" <wait.3>
/ac "Preparatory Touch" <wait.3>
/ac Innovation <wait.2>
/ac "Tricks of the Trade" <wait.3> <condition.excellent>
/ac "Great Strides" <wait.2>
/ac "Byregot's Blessing" <wait.3>
/ac Manipulation <wait.2>
/ac Veneration <wait.2>
/ac Observe <wait.3>
/ac "Focused Synthesis" <wait.3>
/ac Observe <wait.3>
/ac "Focused Synthesis" <wait.3>
/ac Observe <wait.3>
/ac "Focused Synthesis" <wait.3>
/ac "Prudent Synthesis" <wait.3>
/ac "Prudent Synthesis" <wait.3>
/ac "Careful Synthesis" <wait.3>
/ac "Basic Synthesis" <wait.3>
```

Recipe: Golden Silk

I was finding it to occur around 75% of the time

**Comment by TomGreywolfe** [comment]
This seems to occur when the previous craft had hit 100% HQ, and appears to be a bug with the plugin skipping quality increasing skills once 100% HQ is reached. I tested it with a level 1 craft, and 20 out of 20 times it skipped over Reflect.

**Comment by daemitus** [comment]
sorry folks. fix incoming right now.

https://github.com/daemitus/SomethingNeedDoing/blob/master/SomethingNeedDoing/Grammar/Commands/ActionCommand.cs#L196

I need to change how i detect step0 as well, but this should solve the reflect issue.
