### ISSUE TITLE
Quality skip ignore durability

### ISSUE THREAD

**Issue by Pazgabear** [daemitus/SomethingNeedDoing#36]
I have a macro for master recipes that use veneration + 3 groundworks. If the plugin detects the quality has reached 100% before that, it simply skips over everything, including actions that would have allowed manipulation to restore some durability. This results in a failed craft

This is the macro I'm using :
```
/waitaddon "Synthesis" <wait.1>
/require "Well Fed" <wait.1>
/ac Reflect <wait.3>
/ac Manipulation <wait.2>
/ac Innovation <wait.2>
/ac "Basic Touch" <wait.3>
/ac "Standard Touch" <wait.3>
/ac "Advanced Touch" <wait.3>
/ac "Prudent Touch" <wait.3>
/ac Innovation <wait.2>
/ac "Prudent Touch" <wait.3>
/ac "Prudent Touch" <wait.3>
/ac Manipulation <wait.2>
/ac "Preparatory Touch" <wait.3>
/ac Innovation <wait.2>
/ac "Trained Finesse" <wait.3>
/ac "Trained Finesse" <wait.3>
/ac "Great Strides" <wait.2>
/ac "Byregot's Blessing" <wait.3>
/ac Veneration <wait.2>
/ac Groundwork <wait.3>
/ac Groundwork <wait.3>
/ac Groundwork <wait.3>
/ac "Careful Synthesis" <wait.3>
/echo Craft finished <se.2>
/waitaddon "RecipeNote" <wait.0.5>
/click synthesize <wait.2>
/loop

**Comment by daemitus** [comment]
mmmmmm. In the meantime, try frontloading your groundworks after the
manipulation if you have enough durability for a final appraisal + basic at
the end. I probably need to make this configurable in some fashion.

**Comment by daemitus** [comment]
i believe this is fixed now. let me know if you encounter more issues please.
