### ISSUE TITLE
[Suggestion] Sound effect with error messages

### ISSUE THREAD

**Issue by TheF0rg1ven** [daemitus/SomethingNeedDoing#39]
A notification of sorts when for example /requirestats requirement isn't met, or when a macro step doesn't receive a timely response.
Attempting to synthesize with insufficient materials could be flagged as well.

**Comment by daemitus** [comment]
Done. Plays some beeps when the option is enabled. At some point I'll find a way to  play some mp3 or whatever of your choice.
