### ISSUE TITLE
[Feature Request] Auto-Retry on error

### ISSUE THREAD

**Issue by jyudt** [daemitus/SomethingNeedDoing#40]
If your game lags on /ac commands, it will sometimes eat the command and macro will error out.  It would be nice to have some way of resuming the macro automatically instead of having to come back and hit the button.

**Comment by wowee999** [comment]
Second this! Option for <se> play when you get an error would be nice too, but not as crucial.

IDK why I even get error every now and then on random actions mid macro but I'm guessing it's packet loss

**Comment by gurkburk76** [comment]
I've noticed serverlag at times that tends to break stuf flike this very annoing.
Bump on retry action/command x times by itself so i don't have to baby sit it :)

**Comment by daemitus** [comment]
added, let me know how it goes. If the action ends up going through and the response is whats lagged, youll end up using the action twice, but i think its unavoidable.
