### ISSUE TITLE
Commands and what they do?

### ISSUE THREAD

**Issue by Reidlos65** [daemitus/SomethingNeedDoing#41]
/pcraft help does nothing in game and I am wondering what all the extra commands do.  I guess at /loop and /click and assume I know /waitaddon but whats the Recipenote?

**Comment by daemitus** [comment]
Click the help button in the gui. I'll look into why the command is broken

**Comment by Reidlos65** [comment]
I dont see a help button either :(

**Comment by daemitus** [comment]
Near the top, might be a question mark

**Comment by Reidlos65** [comment]
https://imgur.com/a/QqaFKZC

**Comment by daemitus** [comment]
Huh, maybe I fucked up how it is displayed. Start up a macro, it should be
near the stop macro button. Make sure you're up to date on the latest
version too.

**Comment by Reidlos65** [comment]
nada on any button referencing to help etc. Reinstalled aswell to try.  Plugin is 1.2.0.2

**Comment by daemitus** [comment]
Latest is 1.2.2.3.

Check the repo url.
https://github.com/daemitus/MyDalamudPlugins/raw/master/pluginmaster.json

**Comment by Reidlos65** [comment]
that was it.  used a addon to browse repos, musta have been a mirror that wasnt updating or somthing
