### ISSUE TITLE
<echo> doesn't output to /echo channel

### ISSUE THREAD

**Issue by Speshkitty** [daemitus/SomethingNeedDoing#43]
I have multiple chat windows to keep things organised, and `/loop 10 echo` outputs to all visible windows, including windows that do not have echo enabled in chat log settings

Macro used:
```
/waitaddon RecipeNote <wait.0.5-2>
/click Synthesize
/waitaddon Synthesis <wait.0.5>

/runmacro 89/80/3400/7100

/loop 65 <echo>
/echo Craft finished <se.1>
```

Output appears as:
![image](https://user-images.githubusercontent.com/1111285/152169810-b9ac5798-17f4-4de9-971d-817e15a33889.png)

Note the craft finished line in the lower chat window

**Comment by daemitus** [comment]
/loop echo statements specifically goto the echo game channel rather than "general" now.
