### ISSUE TITLE
(BUG / ERROR) "Could not parse percent HQ number in the Synthesis addon..."

### ISSUE THREAD

**Issue by Vaygrim** [daemitus/SomethingNeedDoing#47]
I've been getting this error with higher level Culinarian crafting (level 70 to 74 stuff, class quests.. beast tribe crafting, whatever).

`[SND] Could not parse percent HQ number in the Synthesis add-on: Failure while running /ac "Prudent Touch" (Step 2)`

Macro being  used is as follows:

> /ac "Muscle Memory" <wait.3>
> /ac "Prudent Touch" <wait.3>
> /ac "Manipulation" <wait.2>
> /ac "Careful Synthesis" <wait.3>
> /ac "Prudent Touch" <wait.3>
> /ac "Observe" <wait.3>
> /ac "Focused Touch" <wait.3>
> /ac "Observe" <wait.3>
> /ac "Focused Touch" <wait.3>
> /ac "Innovation" <wait.2>
> /ac "Observe" <wait.3>
> /ac "Focused Touch" <wait.3>
> /ac "Great Strides" <wait.2>
> /ac "Byregot's Blessing" <wait.3>
> /ac "Careful Synthesis" <wait.3>

Yields the above error for steps "Prudent Touch", "Manipulation", "Great Strides" and one other I'm forgetting.
Steps like this stall out and won't run, meaning I've got to manually type out and execute the step (which then works fine). Unsure what is causing it.

If you need further info (versions, whatever), please let me know. Thanks!

**Comment by Vaygrim** [comment]
Nevermind, it appears I might have been a moron and had the wrong option turned on.

SORRY!
LOVE THE MOD, BYE! <3

**Comment by daemitus** [comment]
could you describe what options you did have on? I'm basically taking the
number out of that text box and trying to convert it to a number. It should
be pretty failsafe.

**Comment by Vaygrim** [comment]
I had "Quality Skip" checked under the options. Removing that check fixed the issue. Is that what you need?

**Comment by daemitus** [comment]
Yeah, I'll take a look sometime soon. I think i know whats causing it.
