### ISSUE TITLE
Close click

### ISSUE THREAD

**Issue by ascclemens** [daemitus/SomethingNeedDoing#48]
Most addons have a close button in the top right, which would be useful to be able to click. I didn't see anything to do that, but maybe I missed it. If not, that would be nice to have.

**Comment by daemitus** [comment]
should have one. atleast it does on mine. standard minimize/close.

**Comment by ascclemens** [comment]
Shit, I meant to make this issue on ClickLib. Is it in ClickLib or is it SomethingNeedDoing specific?

**Comment by daemitus** [comment]
clicklib is just pure c#. if theres something missing, its either here or
in another plugin
