### ISSUE TITLE
When importing macro from clipboard and the clipboard contains an image, plugin crashes.

### ISSUE THREAD

**Issue by ThickenNuggets** [daemitus/SomethingNeedDoing#49]
I had an image snip saved in my clipboard, and misclicked "import from clipboard" in the macro editor and the plugin instantly crashed. Was repeatable, happened every time an image was in the clipboard and never when there wasn't. Generic Dalamud error message.

**Comment by daemitus** [comment]
Finally got around to this, thank you :)
