### ISSUE TITLE
Command kinda responds, but doesn't progress beyond that point.

### ISSUE THREAD

**Issue by Kyla772** [daemitus/SomethingNeedDoing#51]
Am trying to doa crafting sessio, but the first line "/waitaddon RecipeNote <wait.0.5>" seems to do it, but then doesn't move past that point in the steps, meaning the macro doesn't work. Am able to use still without this line (having to select it every time), so I'm wondering if the command for such has been updated or whatever.

**Comment by daemitus** [comment]
it waits for the addon to be present. then you send the click.

**Comment by Kyla772** [comment]
It has done the synthesize click, but it just doesn't seem to progress past the addon in the list when I push start on it

**Comment by daemitus** [comment]
whats your whole macro

**Comment by daemitus** [comment]
So you're on the recipe list window, you hit start. which step does it stop
at?

for comparison, this is how mine usually are. I start mine inside the
synthesis window, so its a little different, but you might try waiting for
the Synthesis addon before sending the /ac commands.
```
/require "Well Fed"
/require "Medicated"
/waitaddon "Synthesis" <wait.1>

... crafting stuff...

/waitaddon "RecipeNote" <wait.0.5>
/click synthesize <wait.2>
/loop
```

**Comment by daemitus** [comment]
You should probably add a wait during your /click too, you need to give
your character time to kneel and the actions to be ready to use.

**Comment by Kyla772** [comment]
I've never had to give it a wait time for such things before, and it does seem to work with pretty much anything else, it's just one particular recipe it seems to be having issues with. 

So I'm in the crafting log, have the recipe selected, pres the start button for it, I kneel down and in crafting position, but then nothing. Meanwhile the list has stopped at "/waitaddon RecipeNote" but showing the rest as in the queue.

**Comment by Kyla772** [comment]
Any of the resplendent component B's. It runs fine with the A's and the expert recipes I've done in Firmament, but yeah

**Comment by daemitus** [comment]
Ok. I see whats going on.

I assume you have some of the craft skip options enabled.

Because there isn't a wait between the waitaddon RecipeNote and the action
commands, it skips all of them immediately, because you aren't "crafting"
yet, according to the game. Or  atleast for the condition flag I'm looking
for.

Open up `/xllog` and turn the logging to debug, youll probably see all the
"not crafting skip" messages.

**Comment by daemitus** [comment]
I'm not sure why it works for A/C and not B, but that's what shows up for
me.

**Comment by Kyla772** [comment]
I haven't got a clue as to what I'm looking for in the log or anything.  I have pasted the log to Notepad and copied it here
[xllog.txt](https://github.com/daemitus/SomethingNeedDoing/files/8355857/xllog.txt)

**Comment by daemitus** [comment]
```
16:14:29.686 | DBG [SomethingNeedDoing] Executing: /waitaddon RecipeNote
16:14:29.686 | DBG [SomethingNeedDoing] Sleeping for 500 millis
16:14:30.192 | DBG [SomethingNeedDoing] Executing: /require "well fed"
16:14:30.192 | DBG [SomethingNeedDoing] Executing: /require "medicated"
16:14:30.193 | DBG [SomethingNeedDoing] Executing: /click synthesize
16:14:30.193 | DBG [SomethingNeedDoing] Executing: /ac "Muscle Memory"
16:14:30.193 | DBG [SomethingNeedDoing] Not crafting skip: /ac "Muscle
Memory"  <---
16:14:30.193 | DBG [SomethingNeedDoing] Executing: /ac Manipulation
16:14:30.193 | DBG [SomethingNeedDoing] Not crafting skip: /ac Manipulation
<---
...
16:14:30.193 | DBG [SomethingNeedDoing] Executing: /loop
```

You either need to turn off the option inside the "help" (?) button near
the  top of the window, or add a wait.

**Comment by Kyla772** [comment]
I am an idiot. I was missing a line... I was missing "/waitaddon Synthesis <wait.1>"..... I am so sorrry and thank you for your help....

**Comment by daemitus** [comment]
np :)

**Comment by daemitus** [comment]
`****`
