### ISSUE TITLE
condition not working & garbled double-byte characters

### ISSUE THREAD

**Issue by Crescr** [daemitus/SomethingNeedDoing#52]
condition not working & garbled double-byte characters

We use in Japanese environment.

The condition command is recognized but does not work.
It will be skipped even in a good or excellent state.

Examples:
/ac 集中加工 <wait.3> <condition.good,exllent>

The macro queue successfully displays double-byte characters, but the macro editor displays "????".
Copying to the editor and pasting from the editor work fine, but I'd like you to fix it.

**Comment by daemitus** [comment]
the condition check compares to what is in the synthesis wiindow. does it show up as "good" or as the translated version of that?

The ??? i can work on now. It will end up disabling the monospace font however.

**Comment by daemitus** [comment]
Try <condition.高品質,最高品質> maybe?

**Comment by Crescr** [comment]
thank you for your answer.

I tested it below, but I get a syntax error.
command: /ac 集中加工 <wait.3> <condition.高品質,最高品質>
errormessage: 2番目のターゲット名の指定が正しくありません。： <condition.高品質,最高品質>

If you look at the xldata-addon inspector in the "good" state, it will look like the image.
The "Replace text" field is normal, but the "text:" is garbled and different every time.
I don't know if these are related.

If fixing the font causes other problems
It may be appreciated if you can make a selection system in "Options".
![clip_4](https://user-images.githubusercontent.com/58766640/161189644-391d25ca-e2ee-4f2f-b39c-a867b4e57888.png)

**Comment by daemitus** [comment]
The condition modifier checked for a-zA-Z and did not include the JP character range. I think i've got a good fix ready soon.

**Comment by daemitus** [comment]
Please let me know if `1.2.2.8` fixes your issues. This includes an option to disable monospaced font in the edit window.

**Comment by Crescr** [comment]
Updated to 1.2.2.8.
I have confirmed that all issues have been resolved.

Thank you for the quick response.
