### ISSUE TITLE
Peon has died unexpectedly

### ISSUE THREAD

**Issue by clbx** [daemitus/SomethingNeedDoing#55]
Since updating, every 10-15 minutes I get a "Peon has died unexpectedly" error when a macro is running. 

This is in ``dalamud.log``

```
022-04-18 12:30:00.483 -04:00 [ERR] [SomethingNeedDoing] Unhandled exception occurred
System.NullReferenceException: Node is null
   at SomethingNeedDoing.Grammar.Commands.ActionCommand.GetNodeTextAsInt(AtkTextNode* node, String error)
   at SomethingNeedDoing.Grammar.Commands.ActionCommand.HasMaxProgress()
   at SomethingNeedDoing.Grammar.Commands.ActionCommand.Execute(CancellationToken token)
   at SomethingNeedDoing.Managers.MacroManager.ProcessMacro(ActiveMacro macro, CancellationToken token)
   at SomethingNeedDoing.Managers.MacroManager.EventLoop()
```
Seems like its looking for a UI element that doesn't exist. If there are more descriptive logs somewhere, I can pull those.

I'm keeping a closer eye on it to figure out what its doing/about to do when that happens.

**Comment by daemitus** [comment]
Whats your macro?

If you aren't using a waitaddon before sending crafting commands, the addon likely isnt ready. So yes, the node probably doesn't exist.

**Comment by clbx** [comment]
It happens at random times. The only time I'm waiting for an addon is clicking the synthesize button, but I have not changed my macros, and did not encounter it until post-update. It also crashes when running action commands.

I'll try and get a better idea on when it's crashing, but its usually not when interacting with UI or waiting for an addon.

**Comment by clbx** [comment]
I havent experienced this since yesterday. Not sure what changed, thanks for responding.
