### ISSUE TITLE
[Feature request] Stop loop on 100% spiritbond in a gear piece

### ISSUE THREAD

**Issue by kapsi1** [daemitus/SomethingNeedDoing#59]
As in title, this event logs "Your spiritbond with the x is complete!" to the chat box. Maybe also stop on gear breaking.

**Comment by gurkburk76** [comment]
Was thinking something alongs those lines myself, althought it with the even better if it auto-extracted the materia :)

**Comment by daemitus** [comment]
/requirespiritbond

stops, does not extract.
