### ISSUE TITLE
suggestion, check cp before starting crafting or when food runs out

### ISSUE THREAD

**Issue by gurkburk76** [daemitus/SomethingNeedDoing#62]
It should be possible (i guess) so see if you have enought cp before starting a craft and if so never start it or stop the loop, sometimes you forget to pop food and the craft gets destroyed witch is a sad scenario, same thing if foods stops at craft 345/2345 as an example :)

**Comment by daemitus** [comment]
also, /requirestats craft control cp

**Comment by gurkburk76** [comment]
Oh that's a bit embarrasing, it does say in the help, my bad! :)
