### ISSUE TITLE
[Feature Request] Automatic Unpause

### ISSUE THREAD

**Issue by Kwehh13** [daemitus/SomethingNeedDoing#64]
Are there any plans to make a feature to automatically retry when receiving "[SND] Did not receive a timely response: Failure while running ________"? I usually afk overnight crafting so this would be great

**Comment by daemitus** [comment]
added. let me know how it goes. Depending on when you get hit with lag, the action may end up going through regardless.

**Comment by Kwehh13** [comment]
I'm happy that you took the time to implement this, it's gonna be super useful down the line

Some design flaws I was thinking about when I saw it was added was for example if you turned on infinite retries, what would happen if it was a "not enough materials" error or "inventory full" etc instead of "timely response"

Upon testing I found that it tries to retry these errors, maybe adding a few lines that make sure its strictly an error that is fixable instead of retrying things like not enough mats or inv full or not enough required gp, food and whatnot could be useful, although anyone whos using this feature should just cap it at probably 10 max anyway.

**Comment by daemitus** [comment]
reflecting, theres no real reason to need infinite retries. if it cant fix itself within a minute (realistically like maybe 10 seconds), its not going to fix itself.

**Comment by Kwehh13** [comment]
Agreed. It's already good enough seeing as I don't have to actually be here to craft in general. Just figured it'd be a fun touch to add on
