### ISSUE TITLE
Issue with /ac in CN client

### ISSUE THREAD

**Issue by joesh1n** [daemitus/SomethingNeedDoing#65]
Using the CN client, the crafts were being started from the RecipeNote interface normally, however, when it comes to executing any of the /ac lines, there was an error message of "Could not parse progress number in the Synthesis addon: Failure while running /ac X", with X being the name of the action in Chinese, such as 坚信 for Muscle Memory. Using English macro lines simply don't do anything.
Is there any workaround for this?

**Comment by AsterNighT** [comment]
Same issue here. Would provide info for the problem if necessary.

**Comment by daemitus** [comment]
My best guess is the addon is laid out differently since the patch for your
client. I'll need to write up some steps to figure this out from your end

**Comment by daemitus** [comment]
ok. 
- open the Synthesis window, trial synth is fine. 
- run `/xldata ai`
- On the left hand side of the data window...
  - navigate to "Loaded Units" then "Synthesis"
- On the right hand side of the data window...
  - expand "Node List"
  - the progress nodes are numbers 46, 47, and 48 for me. 46 is max, 47 is current, 48 is the "/" between them. If you expand the node, you can view the text itself for verification. 
  - check that these are as expected, and we can continue troubleshooting.

![Screenshot 2022-04-26 172607](https://user-images.githubusercontent.com/706948/165395493-afbf37fb-361a-4200-9bc7-12ee431d1961.png)

**Comment by daemitus** [comment]
On another note, does using the english names work, or are you required to use the CN ones?
does `/ac "Muscle Memory"` do anything in a regular macro?

**Comment by RyotaMono** [comment]
In CN Client,

for `Progress`:
- Text node 41 is max.
- Text node 42 is current.
- Text node 43 is the "/" sign.

for `Quality`:
- Text node 35 is max.
- Text node 36 is current.
- Text node 37 is the "/" sign.

It is required to use the CN ones, /ac with English skill name results in skill not found error.

**Comment by RyotaMono** [comment]
FYI, the issue may come from the updates in March/April. Old SND client before the /craft was introduced works fine.

**Comment by daemitus** [comment]
Does your synthesis window show the collectability numbers, and have the
different colored quality bar? It sounds like you haven't gotten the update
for it.

**Comment by RyotaMono** [comment]
Thanks for your quick reply. Sorry, I don't quite understand. What is "the update"? Should I post screenshots of both the FFXIV synthesis window and the SND panel?

**Comment by daemitus** [comment]
The 6.1? Game update messed with the synthesis window shifting around some
of the numbers and adding new features. I'll grab a screenshot tomorrow.

**Comment by RyotaMono** [comment]
Not yet, there is a 6-month lag between the update of other global clients and the CN client. Currently, the CN client is at version 6.05.

**Comment by RyotaMono** [comment]
Thanks so much for your hints, and your time to develop the plugin.

I tried the old `AddonSynthesis.cs` file before the recent ffxiv update. Link: [AddonSynthesis.cs](https://github.com/aers/FFXIVClientStructs/commit/fc56dbccb3a51630ebb0a89ddac46e45406d215c). After replacing `lib\FFXIVClientStructs\FFXIVClientStructs\FFXIV\Client\UI\AddonSynthesis.cs` with the older one and rebuild the whole project, the problem is solved.

**Comment by daemitus** [comment]
Ok, i took the old addonsynthesis, built and uploaded as SND 6.05-CN to the repo. It won't get any updates automatically, but is current as of right now. 

Let me know if there are any more problems.

**Comment by yjywybb** [comment]
It seem that you put the same link in _Something Need Doing 6.05 CN_ as _Something Need Doing_

>     
        "Author": "daemitus",
        "Name": "Something Need Doing 6.05 CN",
        "Punchline": "Work work.",
        "Description": "A hard-working peon that crafts what you tell him to. An all-in-one sythesizing solution.",
        "InternalName": "SomethingNeedDoing",
        "AssemblyVersion": "1.2.4.4",
        "RepoUrl": "https://github.com/daemitus/SomethingNeedDoing",
        "ApplicableVersion": "any",
        "DalamudApiLevel": 6,
        "LoadPriority": 0,
        "IconUrl": "https://github.com/daemitus/SomethingNeedDoing/raw/master/res/icon.png",
        "ImageUrls": [],
        "DownloadLinkInstall": "https://github.com/daemitus/MyDalamudPlugins/raw/master/plugins/SomethingNeedDoing/latest.zip",
        "IsHide": false,
        "IsTestingExclusive": false,
        "DownloadLinkTesting": "https://github.com/daemitus/MyDalamudPlugins/raw/master/plugins/SomethingNeedDoing/latest.zip",
        "DownloadLinkUpdate": "https://github.com/daemitus/MyDalamudPlugins/raw/master/plugins/SomethingNeedDoing/latest.zip",
        "DownloadCount": 0,
        "LastUpdate": "1652502386"
