### ISSUE TITLE
[Feature Request]Click command for Retainers.

### ISSUE THREAD

**Issue by xGeekpower** [daemitus/SomethingNeedDoing#75]
If its possible to make a command for each of the retainers on the retainers list, something like
/click retainer_list1 
this plug in works so well for doing my retainers in combination with "yes already" it just that whenever I use the /send NUMPAD command to scroll and pick the retainers if I move my mouse even a tiny bit the cursor starts to fight the mouse and the command of the numpad leading into a macro error, and whenever I use /click commands it seems to never conflict.

**Comment by BeetleLord** [comment]
I submitted an issue with the ClickLib to get us the additional click options we need to better automate the retainer process :)

**Comment by xGeekpower** [comment]
oh nice ty!

**Comment by BeetleLord** [comment]
This has now been implemented, by the way.

**Comment by xGeekpower** [comment]
sorry for the delay reply I took a break from the game, this is amazing ty!
