### ISSUE TITLE
How can I use Japanese in a lua script?

### ISSUE THREAD

**Issue by wmwm-wmwm** [daemitus/SomethingNeedDoing#81]
Using Japanese in lua scripts does not work properly.
If it's not a lua script, it works fine.

```lua
yield('/recipe キャロットラペ')
```

The error statement is:

```
[SND] Failure while running /recipe ??????? (step 5): Recipe not found
```

Please let me know if there is a workaround.

I am sorry if it is rude or inappropriate to you, since I use the online translation site.

**Comment by daemitus** [comment]
https://github.com/daemitus/SomethingNeedDoing/commit/d629c5faad0a90f10b94562ebd50a058a212ca1f
please try version `1.3.0.2`

**Comment by walbi-malbi** [comment]
It's working as expected.
Thanks all for the lighting fast response!

**Comment by wmwm-wmwm** [comment]
It's working as expected.
Thanks all for the lighting fast response!
