### ISSUE TITLE
Lua Function Invalid arguments for method 

### ISSUE THREAD

**Issue by HorseEars** [daemitus/SomethingNeedDoing#83]
I have been trying to fiddle around with the Lua scripting, but either something isn't working quite right with my installation or I don't understand the proper usage for the Lua functions. When I try to call a function like `IsCrafting()` I get results like `[SND] Failure while running script: Invalid arguments to method call`. Even though some of these functions take no arguments.

When I check the types of the functions listed they are luaNet_functions or userdata.

I might just be missing something here, do you have any examples of using these functions?

**Comment by daemitus** [comment]
ok. got a fix for this pending, my own fault. 
going to take a quick stab at other issues before merging
