### ISSUE TITLE
[Feature Request] Get the amount of HQ material already owned

### ISSUE THREAD

**Issue by HakureiHyouga** [daemitus/SomethingNeedDoing#87]
I want to get the amount of HQ synthesis material I have, so that I can loop the "/click synthesis_materialX_hq" to reach that number.
At first I want to use the "GetNodeText" function to get the number, but I found it was a child node.

Is it possible to add a function to get the amount of HQ synthesis material that I already owned, something like
``` C#
public int getHqAmount(int slot)
```

![Snipaste_2022-08-16_02-25-21](https://user-images.githubusercontent.com/12714574/184696068-0bc690ed-5dcd-482c-a8dd-82d11024b329.jpg)

**Comment by daemitus** [comment]
Adding varargs to GetNodeText, so you can get nested nodes.

**Comment by HakureiHyouga** [comment]
> Adding varargs to GetNodeText, so you can get nested nodes.

Thanks! I received this update in game, but when I use this function, an error has happend.
Is there anything wrong with this update? Or is this my fault?😥
![Snipaste_2022-08-23_18-21-39](https://user-images.githubusercontent.com/12714574/186134638-ef0d96cd-9a12-43b7-8f58-93395bf9235e.jpg)

**Comment by daemitus** [comment]
Remove the parenthesis from your numbers
