### ISSUE TITLE
Send modifier not working?

### ISSUE THREAD

**Issue by xGeekpower** [daemitus/SomethingNeedDoing#89]
Hello, I just saw the last update added the ability to send keystrokes combinations but whenever I try it I only get [SND] Unexpected error, so just wondering if I'm doing something wrong I followed the example provided on the help window and still gives me the error, (I'm just trying to make a macro that clicks on a hotbar slot were I have my potion which is a combination Ctrl+Shift+1, I typed 
/send CONTROL+SHIFT+1 but the error just keep showing on the chat) I play on controller but I swapped to keyboard and still the same issue any insight will be appreciated.

**Comment by daemitus** [comment]
Try KEY_1
