### ISSUE TITLE
Tricks of the trade condition outside of good/excellent question

### ISSUE THREAD

**Issue by Dedoooo** [daemitus/SomethingNeedDoing#96]
whats the way to pass on TotT if its not under good/excellent to ensure byregot's doesn't go off on poor condition similarly to a macro? because it stops the craft if it doesn't use it 😅 thanks in advance.

**Comment by guppyfaced** [comment]
You'll want to use conditions, for example:

/ac "Tricks of the trade" <condition.good,excellent>
