### ISSUE TITLE
[Feature Request] Pause for Materia Extraction only if each piece of gear is either at 100% or below a given threshold

### ISSUE THREAD

**Issue by keoShine** [daemitus/SomethingNeedDoing#97]
As /requirespiritbond currently works, looping will _always_ pause for materia extraction if at least two pieces of gear are at 100% spiritbond.. This can be inconvenient if a third piece of gear is about to finish spiritbonding since it requires either stopping to extract materia between crafts multiple separate times or else manually stepping past the /requirespiritbond step a for a few loops.. Since pentamelded gear tends to have 5-10 pieces that are all within 1-2% of each other if they were last Extracted at the same time, it would be more convenient to be able to set a threshold such that the loop will only stop if at least one item is at 100% spiritbond and _no_ items that _aren't_ yet at 100% are above the threshold (e.g., with a threshold of 95%, if Earring, Necklace, Bracelet and Ring 1 are all at 100% and Ring 2 is at 98% due to RNG variance in spiritbond gains, the loop will continue until Ring 2 hits 100% and _then_ pause for Extraction)..

**Comment by daemitus** [comment]
Doesnt it already do this? or is it bugged out?

**Comment by keoShine** [comment]
I may actually just be complete garbage both at reading and figuring out how things work.. Sorry for misunderstanding it and not assuming it was me just being bad at things..
